apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ids-vnf
  namespace: testbed
  labels:
    app: ids-vnf
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ids-vnf
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 20
